# Generated by Django 4.2.7 on 2023-11-23 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iplapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='franchises',
            table='franchises',
        ),
    ]
