# Generated by Django 4.2.7 on 2023-12-11 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iplapp', '0004_userinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='otp',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
